import type { Artifact, ArtifactId, Application, State } from './types';


export const ARTIFACTS: Record<ArtifactId, Artifact> = {
  'answer-major': {
    id: 'answer-major',
    label: 'Your "Why this major?" answer',
    kind: 'do-here',
    status: 'missing',
    owner: 'you',
    estMinutes: 2,
    control: 'textarea',
    prompt: 'Why did you choose your field of study? (250 words) — you wrote this in October for the Buckeye Merit Award. Review it and apply it here.',
  },
  'answer-leadership': {
    id: 'answer-leadership',
    label: 'Ohio Ready Grant — leadership short answer',
    kind: 'do-here',
    status: 'satisfied',
    owner: 'you',
    estMinutes: 2,
    control: 'textarea',
    prompt: 'Describe a time you led without a title. (150 words)',
  },
  'answer-community': {
    id: 'answer-community',
    label: 'Rotary Club — community service answer',
    kind: 'do-here',
    status: 'missing',
    owner: 'you',
    estMinutes: 2,
    control: 'textarea',
    prompt: 'What community are you part of, and what have you given it? (100 words)',
  },
  gpa: {
    id: 'gpa',
    label: 'Enter your GPA',
    kind: 'do-here',
    status: 'missing',
    owner: 'you',
    estMinutes: 1,
    control: 'select',
    prompt: 'Select your cumulative GPA range.',
    options: ['3.00 – 3.24', '3.25 – 3.49', '3.50 – 3.74', '3.75 – 4.00'],
  },
  transcript: {
    id: 'transcript',
    label: 'Official transcript',
    kind: 'confirm',
    status: 'missing',
    owner: 'you',
    outboundLabel: 'Order it from the registrar',
  },
  'rec-alvarez': {
    id: 'rec-alvarez',
    label: 'Recommendation letter',
    kind: 'confirm',
    status: 'requested',
    owner: { name: 'Mr. Alvarez', role: 'AP Chemistry', requestedDaysAgo: 11 },
    nudgeable: true,
  },
  'rec-chen': {
    id: 'rec-chen',
    label: 'Recommendation letter',
    kind: 'confirm',
    status: 'satisfied',
    owner: { name: 'Dr. Chen', role: 'Faculty advisor', requestedDaysAgo: 24 },
  },
  fafsa: {
    id: 'fafsa',
    label: 'FAFSA confirmation page',
    kind: 'confirm',
    status: 'satisfied',
    owner: 'you',
  },
};

export const APPLICATIONS: Application[] = [
  {
    id: 'a1',
    name: 'Hollings Family Scholarship',
    sponsor: 'Hollings Foundation',
    amount: 2500,
    dueInDays: 9,
    needs: ['answer-major', 'transcript'],
    status: 'in_progress',
    matchReasons: ['Engineering major', 'Ohio resident'],
  },
  {
    id: 'a2',
    name: 'Gates Millennium Award',
    sponsor: 'Gates Foundation',
    amount: 5000,
    dueInDays: 14,
    needs: ['answer-major', 'transcript', 'rec-alvarez'],
    status: 'in_progress',
    matchReasons: ['First-generation student', 'GPA 3.25+', 'Pell-eligible'],
  },
  {
    id: 'a3',
    name: 'Coca-Cola Community Award',
    sponsor: 'Coca-Cola Scholars Foundation',
    amount: 1250,
    dueInDays: 12,
    needs: ['answer-major', 'gpa'],
    status: 'in_progress',
    matchReasons: ['Community service hours', 'Sophomore standing'],
  },
  {
    id: 'a4',
    name: 'Ohio Ready Grant',
    sponsor: 'Ohio Department of Higher Education',
    amount: 1500,
    dueInDays: 2,
    needs: ['answer-leadership', 'fafsa'],
    status: 'in_progress',
    matchReasons: ['Ohio resident', 'FAFSA on file'],
  },
  {
    id: 'a5',
    name: 'First-Gen Futures Fund',
    sponsor: 'Futures Fund',
    amount: 3000,
    dueInDays: 6,
    needs: ['rec-alvarez', 'fafsa'],
    status: 'in_progress',
    matchReasons: ['First-generation student'],
  },
  {
    id: 'a6',
    name: 'Rotary Club of Dublin Award',
    sponsor: 'Rotary Club of Dublin',
    amount: 750,
    dueInDays: 3,
    needs: ['answer-community', 'rec-chen'],
    status: 'in_progress',
    matchReasons: ['Franklin County resident', 'Service hours logged'],
  },
  {
    id: 'a7',
    name: 'STEM Persistence Prize',
    sponsor: 'State STEM Council',
    amount: 2000,
    dueInDays: 30,
    needs: ['transcript', 'rec-chen'],
    status: 'in_progress',
    matchReasons: ['Declared STEM major', 'Continuing enrollment'],
  },
  {
    id: 'a8',
    name: 'Buckeye Merit Award',
    sponsor: 'University Alumni Association',
    amount: 1000,
    needs: [],
    status: 'awarded',
    matchReasons: ['GPA 3.25+'],
  },
  {
    id: 'a9',
    name: 'Franklin County Grant',
    sponsor: 'Franklin County Commission',
    amount: 1800,
    needs: [],
    status: 'submitted',
    matchReasons: ['Franklin County resident'],
  },
  {
    id: 'a10',
    name: 'Women in Engineering Scholarship',
    sponsor: 'Society of Women Engineers',
    amount: 4000,
    needs: [],
    status: 'submitted',
    matchReasons: ['Engineering major'],
  },
  {
    id: 'a11',
    name: "Dean's Leadership Award",
    sponsor: 'College of Engineering',
    amount: 2200,
    dueInDays: 18,
    needs: ['transcript'],
    status: 'in_progress',
    matchReasons: ['Nominated by faculty'],
  },
];

export const STUDENT = { firstName: 'Maya', cycle: 'Fall 2026 cycle' };

export const initialState: State = {
  artifacts: ARTIFACTS,
  applications: APPLICATIONS,
  drafts: {},
  openArtifactId: null,
  openArtifactAppId: null,
  expandedAppIds: [],
  filter: 'all',
  lastActed: { artifactId: null, appIds: [], appNames: [], verb: null },
};
